# Generated by Django 2.1.3 on 2019-01-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20190112_1629'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='generationgroup',
            managers=[
            ],
        ),
    ]
